### ISSUE TITLE
Jo attempting to edit your read me!

### ISSUE THREAD

**Issue by JoReavell** [JenPatchett/hello-world#3]

**Comment by JenPatchett** [comment]
@JoReavell what's the difference between an issue and a pull request? Did you raise this issue because it said there was a conflict? Or did GitHub create this issue to alert me? Confused haha!

**Comment by JoReavell** [comment]
I did it. I'm  not sure why. I think you can use this for discussion of any bugs. I a 'heres the issue, I'm going to check out this file and try and fix it' sort of way
